/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(
        name: "BTC_DAI_Reserve"
      ): TruffleContracts.BTC_DAI_ReserveContract;
      require(name: "BTCShifter"): TruffleContracts.BTCShifterContract;
      require(name: "DaiToken"): TruffleContracts.DaiTokenContract;
      require(name: "DEX"): TruffleContracts.DEXContract;
      require(name: "DEXAdapter"): TruffleContracts.DEXAdapterContract;
      require(
        name: "ShifterRegistry"
      ): TruffleContracts.ShifterRegistryContract;
      require(name: "zBTC"): TruffleContracts.zBTCContract;
      require(
        name: "ZEC_DAI_Reserve"
      ): TruffleContracts.ZEC_DAI_ReserveContract;
      require(name: "ZECShifter"): TruffleContracts.ZECShifterContract;
      require(name: "zZEC"): TruffleContracts.zZECContract;
      require(
        name: "BCH_DAI_Reserve"
      ): TruffleContracts.BCH_DAI_ReserveContract;
      require(name: "BCHShifter"): TruffleContracts.BCHShifterContract;
      require(
        name: "BTC_DAI_Reserve"
      ): TruffleContracts.BTC_DAI_ReserveContract;
      require(name: "BTCShifter"): TruffleContracts.BTCShifterContract;
      require(name: "Claimable"): TruffleContracts.ClaimableContract;
      require(name: "DaiToken"): TruffleContracts.DaiTokenContract;
      require(name: "DEX"): TruffleContracts.DEXContract;
      require(name: "DEXAdapter"): TruffleContracts.DEXAdapterContract;
      require(name: "DEXReserve"): TruffleContracts.DEXReserveContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Detailed"): TruffleContracts.ERC20DetailedContract;
      require(name: "ERC20Shifted"): TruffleContracts.ERC20ShiftedContract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "IShifter"): TruffleContracts.IShifterContract;
      require(name: "LinkedList"): TruffleContracts.LinkedListContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "RenToken"): TruffleContracts.RenTokenContract;
      require(name: "Shifter"): TruffleContracts.ShifterContract;
      require(
        name: "ShifterRegistry"
      ): TruffleContracts.ShifterRegistryContract;
      require(name: "TestToken"): TruffleContracts.TestTokenContract;
      require(name: "zBCH"): TruffleContracts.zBCHContract;
      require(name: "zBTC"): TruffleContracts.zBTCContract;
      require(
        name: "ZEC_DAI_Reserve"
      ): TruffleContracts.ZEC_DAI_ReserveContract;
      require(name: "ZECShifter"): TruffleContracts.ZECShifterContract;
      require(name: "zZEC"): TruffleContracts.zZECContract;
      require(
        name: "BTC_DAI_Reserve"
      ): TruffleContracts.BTC_DAI_ReserveContract;
      require(name: "BTCShifter"): TruffleContracts.BTCShifterContract;
      require(name: "DaiToken"): TruffleContracts.DaiTokenContract;
      require(name: "DEX"): TruffleContracts.DEXContract;
      require(name: "DEXAdapter"): TruffleContracts.DEXAdapterContract;
      require(
        name: "ShifterRegistry"
      ): TruffleContracts.ShifterRegistryContract;
      require(name: "zBTC"): TruffleContracts.zBTCContract;
      require(
        name: "ZEC_DAI_Reserve"
      ): TruffleContracts.ZEC_DAI_ReserveContract;
      require(name: "ZECShifter"): TruffleContracts.ZECShifterContract;
      require(name: "zZEC"): TruffleContracts.zZECContract;
      require(
        name: "BTC_DAI_Reserve"
      ): TruffleContracts.BTC_DAI_ReserveContract;
      require(name: "BTCShifter"): TruffleContracts.BTCShifterContract;
      require(name: "DaiToken"): TruffleContracts.DaiTokenContract;
      require(name: "DEX"): TruffleContracts.DEXContract;
      require(name: "DEXAdapter"): TruffleContracts.DEXAdapterContract;
      require(
        name: "ShifterRegistry"
      ): TruffleContracts.ShifterRegistryContract;
      require(name: "zBTC"): TruffleContracts.zBTCContract;
      require(
        name: "ZEC_DAI_Reserve"
      ): TruffleContracts.ZEC_DAI_ReserveContract;
      require(name: "ZECShifter"): TruffleContracts.ZECShifterContract;
      require(name: "zZEC"): TruffleContracts.zZECContract;
    }
  }
}
